ui-network:
  resource-directory: build/dhash/
p2p:
  dhash:
    resource-directory: build/dhash/
communication:
  socket:
    instances:
      dhash:
        response_time: 2000
        buffer_size_multicast: 1024
        ip_multicast: 224.0.0.1
        port_multicast: 22011
        timeout_tcp_connection: 2000
        port_tcp: 22013
        size_tcp_buffer: 1024